#!/bin/bash
#Evaluate-STIG on Linux using Bash

function usage() {
cat << EOF
--ScanType <"Unclassified"|"Classified">
        Use to instruct Evaluate-STIG the classification of the asset.  Valid ScanTypes are "Unclassified" and "Classified".  If not specified, default will be "Unclassified".

--Marking <String>
        Use to optionally set Marking in CKL and on header/footer of files generated by Evaluate-STIG.  Example use is "CUI"/"Confidential"/"Secret"/"Top Secret" but accepts any marking string.

--TargetComments <String>
        Use to optionally set the Target Comments field in CKL|CKLB outputs.

--VulnTimeout <int>
        Maximum time in minutes to allow a singular Vuln ID check to run.  Default is 15.

--FileSearchTimeout <int>
        Maximum time in minutes (1-1440) for file type search run during prescan.  Default is 240.  This is for checks requiring that all hard disks be searched for specific file types (e.g. .pfx).

--AnswerKey <String>
        Use to instruct Evaluate-STIG which Answer Key to use for determining if a comment from an answer file should be applied.  Answer Keys are per Vuln ID and user-defined within the answer file.  If not specified, default Answer Key will be "DEFAULT".  Refer to documentation for more information.

--AFPath <String>
        Path to Answer Files.  If not specified, defaults to \$PsScriptRoot\\AnswerFiles.

--Output <"Console"|"CKL"|"CKLB"|"CSV"|"XCCDF"|"CombinedCKL"|"CombinedCKLB"|"CombinedCSV"|"STIGManager"|"Splunk"|"Summary">
        Specify output type(s).  Use comma separation for multiple.  If not specified, output will be returned to console.

--OutputPayload <"Title"|"Version"|"ReleaseDate"|"Classification"|"HostName"|"Site"|"Instance"|"IP"|"MAC"|"FQDN"|"Role"|"GroupID"|"GroupTitle"|"RuleID"|"STIGID"|"Severity"|"SeverityOverride"|"Justification"|"LegacyIDs"|"RuleTitle"|"Discussion"|"CheckText"|"FixText"|"CCI"|"Status"|"FindingDetails"|"Comments|"ESVersion"|"StartTime">
        Specify which fields to output when outputing to CSV, JSON, or Splunk.  Order of fields will be retained from command line.  For multiple, separate with commas.  Default is all fields.  Requires -Output CSV|CombinedCSV|Splunk or -JSON.

--OutputPath <String>
        Sets the directory path for Evaluate-STIG to save its results.  May be a local or UNC path.  If not specified, default path will be C:\\Users\\Public\\Public Documents or \\opt\\.

--JSON
        Output Console Object in JSON Format using OutputPayload Options.  JSON Objects are based on Group ID

--PreviousToKeep <int>
        Number of previous scan results to retain.  Default is 0.  Requires -Output.

--AllowDeprecated
        Enable scanning of STIGs that are no longer available on cyber.mil (deprecated).  By default, deprecated STIGs will not be scanned.

--AllowSeverityOverride
        Enables the use of the Severity Override and Justification fields in checklists.

--AllowIntegrityViolations
        Ignores Evaluate-STIG file integrity validation failures and allows the scan to continue.

--SelectSTIG <String>
        Specify which STIG(s) to scan.  For multiple STIGs, separate with commas.  Cannot be specified with --ExcludeSTIG.

--ExcludeSTIG <String>
        Specify which STIG(s) to exclude from the scan.  For multiple STIGs, separate with commas.  Cannot be specified with --SelectSTIG.

--ForceSTIG <String>
        Ignore detection of STIG applicability and forcefully run a scan of selected STIG(s). For multiple STIGs, separate with commas.  *WARNING* Evaluate-STIG results are not guaranteed with this option.  Use at own risk. *WARNING*

--SelectVuln <String>
        Specify which Vulnerabilities(s) to scan (V-#####).  For multiple Vulnerabilities, separate with commas.  Can only be used with --SelectSTIG.

--ExcludeVuln <String>
        Specify which Vulnerabilities(s) to exclude from a scan (V-#####).  For multiple Vulnerabilities, separate with commas.  Can only be used with --SelectSTIG.

--CiscoConfig <String>
        Execute a scan of Cisco show tech files.  May be a path to a single file, a folder, or combination using comma separation.

--SelectDeviceType
        Specify a device type for IOS, IOS-XE Catalyst 9k series, and IOS-XE ISR device specific Cisco configs. Use comma separation for multiple.  Requires -CiscoConfig.

--ThrottleLimit <int>
        Number of concurrent Evaluate-STIG jobs to run when using --CiscoConfig.  Default is 10.

--SMCollection <String>
        Use to instruct Evaluate-STIG which STIGManager Collection to upload results.

--SMPassphrase <String>
        Passphrase to decrpyt private key if encrypted .key is used for authentication to a STIGManager instance.

--SplunkHECName <String>
        Use to instruct Evaluate-STIG which Splunk Collector to upload results.  Requires -Output Splunk.

--ApplyTattoo
        Applies Evaluate-STIG tattooing on system.  Mainly for providing a detection method to configuration management tools.

--ListSupportedProducts
        Lists all products that Evaluate-STIG currently supports.

--ListApplicableProducts
        Lists all Evaluate-STIG supported STIGs that are applicable to the asset.

--Version
        Display Evaluate-STIG version and running path.

--Update
        Downloads updates to Evaluate-STIG from the Evaluate-STIG repo on SPORK.

--LocalSource
        Directs -Update to download updates to Evaluate-STIG from a local Evaluate-STIG directory.

--DownloadPS
        Specify whether or not to download PowerShell binary archive automatically. Script exits after download.

--Proxy <String>
        Configure proxy for use with --Update and --DownloadPS

--PSPath
        Path to directory containing PowerShell executable, 'pwsh'.

Evaluate-STIG
        https://spork.navsea.navy.mil/nswc-crane-division/evaluate-stig
        https://intelshare.intelink.gov/sites/NAVSEA-RMF
EOF

exit 1
}

SHELLNOCASEMATCH=$(shopt -p nocasematch; true)
shopt -s nocasematch
optspec=":h-:"
while getopts "$optspec" args; do
    case "${args}" in
        -)
            case ${OPTARG} in
                ScanType) ScanType="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                Marking) Marking="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                TargetComments) TargetComments="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                AnswerKey) AnswerKey="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                AFPath) AFPath="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                Output) Output="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                OutputPath) OutputPath="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                OutputPayload) OutputPayload="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                JSON) JSON=true ;;
                PreviousToKeep) PreviousToKeep="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                AllowDeprecated) AllowDeprecated=true ;;
                AllowSeverityOverride) AllowSeverityOverride=true ;;
                AllowIntegrityViolations) AllowIntegrityViolations=true ;;
                SelectSTIG) SelectSTIG="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                ExcludeSTIG) ExcludeSTIG="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                ForceSTIG) ForceSTIG="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                VulnTimeout) VulnTimeout="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                FileSearchTimeout) FileSearchTimeout="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                CiscoConfig) CiscoConfig="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                SelectDeviceType) SelectDeviceType="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                ThrottleLimit) ThrottleLimit="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                SelectVuln) SelectVuln="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                ExcludeVuln) ExcludeVuln="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                PSPath) PSPath="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                SMCollection) SMCollection="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                SMPassphrase) SMPassphrase="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                SplunkHECName) SplunkHECName="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                ApplyTattoo) ApplyTattoo=true ;;
                ListSupportedProducts) ListSupportedProducts=true ;;
                ListApplicableProducts) ListApplicableProducts=true ;;
                Version) Version=true ;;
                Update) Update=true ;;
                LocalSource) LocalSource="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                DownloadPS) DownloadPS=true ;;
                Proxy) Proxy="${!OPTIND}"; OPTIND=$(( $OPTIND +1 )) ;;
                Help) usage ;;
                *)
                    echo -e "\e[31m[ FAILED ]\tError in command line parsing.  Incorrect switch used.\e[0m" >&2
                    exit 1
            esac;;
        h)
            usage ;;
        help)
            usage ;;
        *)
            echo -e "\e[31m[ FAILED ]\tError in second command line parsing (2 tacks?)\e[0m" >&2
            exit 1
    esac
done

$SHELLNOCASEMATCH

if (($EUID != 0)); then
    echo -e "\e[31m[ FAILED ]\tMust be run with sudo privileges.\e[0m"
    exit 1
fi

ESArgs=""
ESPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ESUSER=$(logname)
SIMPHOST=$(hostnamectl --static | cut -d "." -f1)
VERSION_LIMIT=3.0
CURRENT_VERSION=$(uname -r | cut -c1-3)

#Check for noexec
MOUNT_MODE=`findmnt -T $ESPATH | grep noexec`
if [[ ! -z "$MOUNT_MODE" ]]; then
        echo -e "\e[31m[ FAILED ]\tMust be run from a partition mounted without 'noexec'\e[0m"
        exit 1
fi

if [ "$DownloadPS" = "true" ]; then
    if [[ $Proxy = "" ]]; then
        LATEST_RELEASE=$(curl --retry 5 --retry-delay 5 -L -s -H 'Accept: application/json' https://github.com/PowerShell/PowerShell/releases/latest)
    else
        LATEST_RELEASE=$(curl --retry 5 --retry-delay 5 -L --proxy $Proxy -s -H 'Accept: application/json' https://github.com/PowerShell/PowerShell/releases/latest)
    fi

    LATEST_VERSION=$(echo "$LATEST_RELEASE" | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

    if (( $(echo "$CURRENT_VERSION < 4.0" | bc -l) )); then #PS 7.4 is not supported on RHEL 7. When LTS is 7.3, default to LTS
        LATEST_VERSION="v7.3.10"
    fi

    ARTIFACT_URL="https://github.com/PowerShell/PowerShell/releases/download/$LATEST_VERSION/powershell$(echo $LATEST_VERSION | tr v -)-linux-x64.tar.gz"

    if [ -f "$ESPATH/powershell.tar.gz" ] ; then rm $ESPATH/powershell.tar.gz; fi
    if [[ $Proxy = "" ]]; then
        if ! curl --retry 5 --retry-delay 5 -L -o $ESPATH/powershell.tar.gz $ARTIFACT_URL; then
            echo -e "\e[31m[ FAILED ]\tPowerShell archive failed to download.\e[0m"
            exit 1
        fi
    else
        if ! curl -L --retry 5 --retry-delay 5 --proxy $Proxy -o $ESPATH/powershell.tar.gz $ARTIFACT_URL; then
            echo -e "\e[31m[ FAILED ]\tPowerShell archive failed to download.\e[0m"
            exit 1
        fi
    fi
    chown $ESUSER: $ESPATH/powershell.tar.gz
    exit 0
fi

if (( $(echo "$CURRENT_VERSION < $VERSION_LIMIT" | bc -l) )); then
    echo -e "\e[31m[ FAILED ]\tKernel version not supported.\e[0m"
    exit 1
fi

PWSHPath=$(readlink -f $(which pwsh 2>/dev/null) 2>/dev/null)

if [[ $PWSHPath = "" ]]; then
    if [[ $PSPath = "" ]]; then
        POWERSHELL=$(find -H $ESPATH -name powershell.tar.gz)

        if [ -d "$ESPATH/powershell" ]; then
            rm -rf $ESPATH/powershell
        fi

        if [ -z "$POWERSHELL" ]; then
            echo -e "\e[31m[ FAILED ]\tPrerequisite failed.  PowerShell binary archive not found in $ESPATH.\e[0m"
            echo -e "\e[33[ ALERT  ]\tUse the '--DownloadPS' switch or download tar.gz archive, rename to 'powershell.tar.gz' and place in $ESPATH.\e[0m"
            echo -e "\e[33[ ALERT  ]\thttps://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.4#binary-archives\e[0m"
            exit 1
        fi

        mkdir $ESPATH/powershell

        tar zxf $POWERSHELL -C $ESPATH/powershell

        PSEXECPATH=$ESPATH/powershell

        chown -R root: $PSEXECPATH #ensure archive directory has a valid owner and group
    else
        if [ -d $PSPath ]; then
            if [[ -z $(find -H $PSPath -name pwsh) ]]; then
                echo -e "\e[31m[ FAILED ]\tPrerequisite failed.  PowerShell executable not found in $PSPath.\e[0m"
                exit 1
            else
                PSEXECPATH=$PSPath
            fi
        else
            echo -e "\e[31m[ FAILED ]\tPrerequisite failed. $PSPath is not a valid directory.\e[0m"
            exit 1
        fi
    fi

    chmod +x $PSEXECPATH/pwsh
else
    PSEXECPATH=$(dirname $(readlink -f $(which pwsh)))
fi

if [[ ! $ScanType = "" ]]; then ESArgs+=" -ScanType $ScanType"; fi
if [[ ! $Marking = "" ]]; then ESArgs+=" -Marking $Marking"; fi
if [[ ! $TargetComments = "" ]]; then ESArgs+=" -TargetComments $TargetComments"; fi
if [[ ! $AnswerKey = "" ]]; then ESArgs+=" -AnswerKey $AnswerKey"; fi
if [[ ! $AFPath = "" ]]; then ESArgs+=" -AFPath $AFPath"; fi
if [[ ! $Output = "" ]]; then ESArgs+=" -Output $Output"; fi
if [[ ! $OutputPath = "" ]]; then ESArgs+=" -OutputPath $OutputPath"; fi
if [[ ! $OutputPayload = "" ]]; then ESArgs+=" -OutputPayload $OutputPayload"; fi
if [[ ! $JSON = "" ]]; then ESArgs+=" -JSON"; fi
if [[ ! $PreviousToKeep = "" ]]; then ESArgs+=" -PreviousToKeep $PreviousToKeep"; fi
if [[ ! $AllowDeprecated = "" ]]; then ESArgs+=" -AllowDeprecated"; fi
if [[ ! $AllowSeverityOverride = "" ]]; then ESArgs+=" -AllowSeverityOverride"; fi
if [[ ! $AllowIntegrityViolations = "" ]]; then ESArgs+=" -AllowIntegrityViolations"; fi
if [[ ! $SelectSTIG = "" ]]; then ESArgs+=" -SelectSTIG $SelectSTIG"; fi
if [[ ! $ExcludeSTIG = "" ]]; then ESArgs+=" -ExcludeSTIG $ExcludeSTIG"; fi
if [[ ! $ForceSTIG = "" ]]; then ESArgs+=" -ForceSTIG $ForceSTIG"; fi
if [[ ! $VulnTimeout = "" ]]; then ESArgs+=" -VulnTimeout $VulnTimeout"; fi
if [[ ! $FileSearchTimeout = "" ]]; then ESArgs+=" -FileSearchTimeout $FileSearchTimeout"; fi
if [[ ! $CiscoConfig = "" ]]; then ESArgs+=" -CiscoConfig $CiscoConfig"; fi
if [[ ! $SelectDeviceType = "" ]]; then ESArgs+=" -SelectDeviceType $SelectDeviceType"; fi
if [[ ! $ThrottleLimit = "" ]]; then ESArgs+=" -ThrottleLimit $ThrottleLimit"; fi
if [[ ! $SelectVuln = "" ]]; then ESArgs+=" -SelectVuln $SelectVuln"; fi
if [[ ! $ExcludeVuln = "" ]]; then ESArgs+=" -ExcludeVuln $ExcludeVuln"; fi
if [[ ! $SMCollection = "" ]]; then ESArgs+=" -SMCollection $SMCollection"; fi
if [[ ! $SMPassphrase = "" ]]; then ESArgs+=" -SMPassphrase $SMPassphrase"; fi
if [[ ! $SplunkHECName = "" ]]; then ESArgs+=" -SplunkHECName $SplunkHECName"; fi
if [[ ! $ApplyTattoo = "" ]]; then ESArgs+=" -ApplyTattoo"; fi
if [[ ! $LocalSource = "" ]]; then ESArgs+=" -LocalSource $LocalSource"; fi
if [[ ! $Proxy = "" ]]; then ESArgs+=" -Proxy $Proxy"; fi

if [ "$ListSupportedProducts" = "true" ]; then
    ESArgs=" -ListSupportedProducts";
    $PSEXECPATH/pwsh $ESPATH/Evaluate-STIG.ps1 $ESArgs
elif [ "$ListApplicableProducts" = "true" ]; then
    ESArgs=" -ListApplicableProducts";
    $PSEXECPATH/pwsh $ESPATH/Evaluate-STIG.ps1 $ESArgs
elif [ "$Version" = "true" ]; then
    ESArgs=" -Version";
    $PSEXECPATH/pwsh $ESPATH/Evaluate-STIG.ps1 $ESArgs
elif [ "$Update" = "true" ]; then
    ESArgs=" -Update";
    if [[ ! $LocalSource = "" ]]; then
        ESArgs+=" -LocalSource $LocalSource"
    fi
    if [[ ! $Proxy = "" ]]; then
        ESArgs+=" -Proxy $Proxy"
    fi
    $PSEXECPATH/pwsh $ESPATH/Evaluate-STIG.ps1 $ESArgs
elif [ "$Output" = "" ]; then
    $PSEXECPATH/pwsh $ESPATH/Evaluate-STIG.ps1 $ESArgs
else
    if [ -d $OutputPath/_Partial_${SIMPHOST^^} ]; then HOSTPATH="_Partial_{$SIMPHOST^^}"; else HOSTPATH=${SIMPHOST^^}; fi
    $PSEXECPATH/pwsh $ESPATH/Evaluate-STIG.ps1 $ESArgs && if [[ $OutputPath ]]; then chown -R $ESUSER: $OutputPath/$HOSTPATH; else chown -R $ESUSER: /opt/STIG_Compliance; fi
fi

if [[ $PWSHPath = "" ]] && [[ $PSPath = "" ]]; then
    rm -rf $PSEXECPATH
fi